### ISSUE TITLE
Projektlink in Hauptnavigation führt zur Serverfehler

### ISSUE THREAD

**Issue by innosmith** [decidim-swiss/decidim.swiss#115]
Die URL https://test.impulskoeniz.ch/processes auf der Testplattform führt zu einem Serverfehler. Es gibt zeitlich aktive und sichtbare Projekte, weshalb uns nicht klar ist, weshalb dieser Fehler auftritt. Auf der Startseite werden die Projekte angezeigt.

**Comment by carlobeltrame** [comment]
Stack Trace:
```
[fa1e0b85-84bb-42dd-9c5f-2fa25adb90f2] ActionView::Template::Error (undefined method `tenant_type' for #<Decidim::ParticipatoryProcess id: 143, slug: "plattformfreiraum", hashtag: "", decidim_organization_id: 6, created_at: "2023-10-03 16:09:02.895706000 +0200", updated_at: "2023-10-05 15:07:06.019755000 +0200", title: {"de"=>"Testprojekt Plattform Freiraum"}, subtitle: {"de"=>"testprojekt"}, short_description: {"de"=>"<p>beschreibung</p>"}, description: {"de"=>"<p>beschreibung</p>"}, hero_image: nil, banner_image: nil, promoted: false, published_at: "2023-10-03 16:17:29.582757000 +0200", developer_group: {"de"=>""}, end_date: "2025-12-20", meta_scope: {"de"=>""}, local_area: {"de"=>""}, target: {"de"=>""}, participatory_scope: {"de"=>""}, participatory_structure: {"de"=>""}, decidim_scope_id: nil, decidim_participatory_process_group_id: nil, show_statistics: false, announcement: {"de"=>""}, scopes_enabled: false, start_date: "2023-10-03", private_space: false, reference: "impulskoeniz-PART-2023-10-143", d...
[fa1e0b85-84bb-42dd-9c5f-2fa25adb90f2] 1: <%= card_for participatory_process %>
[fa1e0b85-84bb-42dd-9c5f-2fa25adb90f2]
[fa1e0b85-84bb-42dd-9c5f-2fa25adb90f2] app/cells/decidim_ocl/participatory_processes/process_m_cell.rb:26:in `default_image'
[fa1e0b85-84bb-42dd-9c5f-2fa25adb90f2] app/cells/decidim_ocl/participatory_processes/process_m_cell.rb:16:in `rescue in resource_image_path'
[fa1e0b85-84bb-42dd-9c5f-2fa25adb90f2] app/cells/decidim_ocl/participatory_processes/process_m_cell.rb:11:in `resource_image_path'
```

**Comment by larsUE** [comment]
Bitte den Zusammenhang mit #107 prüfen. Vielleicht hat das transparente Card Image, welches @Kagemaru eingespielt hat (und leider noch nicht richtig funktioniert ;) ) was damit zu tun.

**Comment by carlobeltrame** [comment]
Habe das Problem von diesem Issue gefunden und auf INT gefixt.

Einen Zusammenhang mit #107 sehe ich nicht, hier war das Problem bei den Default-Bildern von Partizipationsprozessen, während in #107 das Problem eher bei Profilbildern zu liegen scheint. Leider ist seit der letzten wieder-eröffnung von #107 nicht dokumentiert, was das genaue Problem ist, bzw. habe ich auch gar keinen Account auf Cokreation Winterthur INT, um das nachstellen zu können.

**Comment by innosmith** [comment]
Danke @carlobeltrame , funktioniert! War es ein Software-Fehler und braucht ein PROD-Deployment (obwohl dort alles funktioniert?). Bitte Ticket entsprechend kennzeichnen.

**Comment by carlobeltrame** [comment]
Es war ein Problem mit der Logik, welche das Fallback-Bild für Prozesse ohne Bild berechnet. Bei Tenants für welche wir im Code kein Fallback-Bild hinterlegt hatten, und auch kein Bild im Highlighted Content Banner hochgeladen wurde, konnte dieses Problem auftreten. Ich habe jetzt für alle bisherigen Tenants ein Fallback-Bild erfasst (vorerst mal das von Luzern).
