### ISSUE TITLE
500er auf Komponentenseite

### ISSUE THREAD

**Issue by larsUE** [decidim-swiss/decidim.swiss#117]
Diese Backendseite generiert einen 500er: https://cokreation.winterthur.ch/admin/participatory_processes/marktplatz/components/470/manage/

**Comment by larsUE** [comment]
Hier das allenfalls betroffene Porposal: https://cokreation.winterthur.ch/processes/marktplatz/f/470/proposals/886

**Comment by carlobeltrame** [comment]
<details>
<summary>Stack Trace</summary>
```
[7999da70-27b5-44b2-b057-1fe9e3d99827] ActionView::Template::Error (nil can't be converted to a Time value):
[7999da70-27b5-44b2-b057-1fe9e3d99827] 34: <% elsif proposal.accepted? || proposal.rejected? %>
[7999da70-27b5-44b2-b057-1fe9e3d99827] 35: <div class="help-text-overdue text-success">
[7999da70-27b5-44b2-b057-1fe9e3d99827] 36: <%= t("decidim.reporting_proposals.admin.resolution_time") %>:
[7999da70-27b5-44b2-b057-1fe9e3d99827] 37: <%= time_elapsed_to_answer(proposal) %>
[7999da70-27b5-44b2-b057-1fe9e3d99827] 38: </div>
[7999da70-27b5-44b2-b057-1fe9e3d99827] 39: <% end %>
[7999da70-27b5-44b2-b057-1fe9e3d99827] 40: </div>
[7999da70-27b5-44b2-b057-1fe9e3d99827]
[7999da70-27b5-44b2-b057-1fe9e3d99827] actionview (6.1.7.4) lib/action_view/helpers/date_helper.rb:697:in `normalize_distance_of_time_argument_to_time'
[7999da70-27b5-44b2-b057-1fe9e3d99827] actionview (6.1.7.4) lib/action_view/helpers/date_helper.rb:100:in `distance_of_time_in_words'
[7999da70-27b5-44b2-b057-1fe9e3d99827] decidim-module-reporting-proposals (57d3080ac0e4) app/helpers/concerns/decidim/reporting_proposals/admin/proposals_helper_override.rb:56:in `time_elapsed_to_answer'
[7999da70-27b5-44b2-b057-1fe9e3d99827] decidim-module-reporting-proposals (57d3080ac0e4) app/views/decidim/reporting_proposals/admin/proposals/_proposal_td_title.html.erb:37
[7999da70-27b5-44b2-b057-1fe9e3d99827] actionview (6.1.7.4) lib/action_view/base.rb:247:in `public_send'
[7999da70-27b5-44b2-b057-1fe9e3d99827] actionview (6.1.7.4) lib/action_view/base.rb:247:in `_run'
[7999da70-27b5-44b2-b057-1fe9e3d99827] actionview (6.1.7.4) lib/action_view/template.rb:154:in `block in render'
[7999da70-27b5-44b2-b057-1fe9e3d99827] activesupport (6.1.7.4) lib/active_support/notifications.rb:205:in `instrument'
[7999da70-27b5-44b2-b057-1fe9e3d99827] actionview (6.1.7.4) lib/action_view/template.rb:345:in `instrument_render_template'
[7999da70-27b5-44b2-b057-1fe9e3d99827] actionview (6.1.7.4) lib/action_view/template.rb:152:in `render'
[7999da70-27b5-44b2-b057-1fe9e3d99827] actionview (6.1.7.4) lib/action_view/renderer/partial_renderer.rb:285:in `block in render_partial_template'
[7999da70-27b5-44b2-b057-1fe9e3d99827] activesupport (6.1.7.4) lib/active_support/notifications.rb:205:in `instrument'
[7999da70-27b5-44b2-b057-1fe9e3d99827] actionview (6.1.7.4) lib/action_view/renderer/partial_renderer.rb:280:in `render_partial_template'
[7999da70-27b5-44b2-b057-1fe9e3d99827] actionview (6.1.7.4) lib/action_view/renderer/partial_renderer.rb:271:in `render'
[7999da70-27b5-44b2-b057-1fe9e3d99827] actionview (6.1.7.4) lib/action_view/renderer/renderer.rb:81:in `render_partial_to_object'
[7999da70-27b5-44b2-b057-1fe9e3d99827] actionview (6.1.7.4) lib/action_view/renderer/renderer.rb:53:in `render_partial'
[7999da70-27b5-44b2-b057-1fe9e3d99827] actionview (6.1.7.4) lib/action_view/helpers/rendering_helper.rb:45:in `render'
[7999da70-27b5-44b2-b057-1fe9e3d99827] decidim-proposals (0.27.4) app/views/decidim/proposals/admin/proposals/_proposal-tr.html.erb:10
[7999da70-27b5-44b2-b057-1fe9e3d99827] actionview (6.1.7.4) lib/action_view/base.rb:247:in `public_send'
[7999da70-27b5-44b2-b057-1fe9e3d99827] actionview (6.1.7.4) lib/action_view/base.rb:247:in `_run'
[7999da70-27b5-44b2-b057-1fe9e3d99827] actionview (6.1.7.4) lib/action_view/template.rb:154:in `block in render'
[7999da70-27b5-44b2-b057-1fe9e3d99827] activesupport (6.1.7.4) lib/active_support/notifications.rb:205:in `instrument'
[7999da70-27b5-44b2-b057-1fe9e3d99827] actionview (6.1.7.4) lib/action_view/template.rb:345:in `instrument_render_template'
[7999da70-27b5-44b2-b057-1fe9e3d99827] actionview (6.1.7.4) lib/action_view/template.rb:152:in `render'
[7999da70-27b5-44b2-b057-1fe9e3d99827] actionview (6.1.7.4) lib/action_view/renderer/partial_renderer.rb:285:in `block in render_partial_template'
[7999da70-27b5-44b2-b057-1fe9e3d99827] activesupport (6.1.7.4) lib/active_support/notifications.rb:205:in `instrument'
[7999da70-27b5-44b2-b057-1fe9e3d99827] actionview (6.1.7.4) lib/action_view/renderer/partial_renderer.rb:280:in `render_partial_template'
[7999da70-27b5-44b2-b057-1fe9e3d99827] actionview (6.1.7.4) lib/action_view/renderer/partial_renderer.rb:271:in `render'
[7999da70-27b5-44b2-b057-1fe9e3d99827] actionview (6.1.7.4) lib/action_view/renderer/renderer.rb:81:in `render_partial_to_object'
[7999da70-27b5-44b2-b057-1fe9e3d99827] actionview (6.1.7.4) lib/action_view/renderer/renderer.rb:27:in `render_to_object'
[7999da70-27b5-44b2-b057-1fe9e3d99827] actionview (6.1.7.4) lib/action_view/renderer/renderer.rb:22:in `render'
[7999da70-27b5-44b2-b057-1fe9e3d99827] actionview (6.1.7.4) lib/action_view/helpers/rendering_helper.rb:38:in `block in render'
[7999da70-27b5-44b2-b057-1fe9e3d99827] actionview (6.1.7.4) lib/action_view/base.rb:273:in `in_rendering_context'
[7999da70-27b5-44b2-b057-1fe9e3d99827] actionview (6.1.7.4) lib/action_view/helpers/rendering_helper.rb:34:in `render'
[7999da70-27b5-44b2-b057-1fe9e3d99827] decidim-proposals (0.27.4) app/views/decidim/proposals/admin/proposals/index.html.erb:76
[7999da70-27b5-44b2-b057-1fe9e3d99827] activerecord (6.1.7.4) lib/active_record/relation/delegation.rb:88:in `each'
[7999da70-27b5-44b2-b057-1fe9e3d99827] activerecord (6.1.7.4) lib/active_record/relation/delegation.rb:88:in `each'
[7999da70-27b5-44b2-b057-1fe9e3d99827] decidim-proposals (0.27.4) app/views/decidim/proposals/admin/proposals/index.html.erb:75
[7999da70-27b5-44b2-b057-1fe9e3d99827] actionview (6.1.7.4) lib/action_view/base.rb:247:in `public_send'
[7999da70-27b5-44b2-b057-1fe9e3d99827] actionview (6.1.7.4) lib/action_view/base.rb:247:in `_run'
[7999da70-27b5-44b2-b057-1fe9e3d99827] actionview (6.1.7.4) lib/action_view/template.rb:154:in `block in render'
[7999da70-27b5-44b2-b057-1fe9e3d99827] activesupport (6.1.7.4) lib/active_support/notifications.rb:205:in `instrument'
[7999da70-27b5-44b2-b057-1fe9e3d99827] actionview (6.1.7.4) lib/action_view/template.rb:345:in `instrument_render_template'
[7999da70-27b5-44b2-b057-1fe9e3d99827] actionview (6.1.7.4) lib/action_view/template.rb:152:in `render'
[7999da70-27b5-44b2-b057-1fe9e3d99827] actionview (6.1.7.4) lib/action_view/renderer/template_renderer.rb:61:in `block (2 levels) in render_template'
[7999da70-27b5-44b2-b057-1fe9e3d99827] activesupport (6.1.7.4) lib/active_support/notifications.rb:205:in `instrument'
[7999da70-27b5-44b2-b057-1fe9e3d99827] actionview (6.1.7.4) lib/action_view/renderer/template_renderer.rb:56:in `block in render_template'
[7999da70-27b5-44b2-b057-1fe9e3d99827] actionview (6.1.7.4) lib/action_view/renderer/template_renderer.rb:71:in `block in render_with_layout'
[7999da70-27b5-44b2-b057-1fe9e3d99827] activesupport (6.1.7.4) lib/active_support/notifications.rb:205:in `instrument'
[7999da70-27b5-44b2-b057-1fe9e3d99827] actionview (6.1.7.4) lib/action_view/renderer/template_renderer.rb:70:in `render_with_layout'
[7999da70-27b5-44b2-b057-1fe9e3d99827] actionview (6.1.7.4) lib/action_view/renderer/template_renderer.rb:55:in `render_template'
[7999da70-27b5-44b2-b057-1fe9e3d99827] actionview (6.1.7.4) lib/action_view/renderer/template_renderer.rb:11:in `render'
[7999da70-27b5-44b2-b057-1fe9e3d99827] actionview (6.1.7.4) lib/action_view/renderer/renderer.rb:61:in `render_template_to_object'
[7999da70-27b5-44b2-b057-1fe9e3d99827] actionview (6.1.7.4) lib/action_view/renderer/renderer.rb:29:in `render_to_object'
[7999da70-27b5-44b2-b057-1fe9e3d99827] actionview (6.1.7.4) lib/action_view/rendering.rb:117:in `block in _render_template'
[7999da70-27b5-44b2-b057-1fe9e3d99827] actionview (6.1.7.4) lib/action_view/base.rb:273:in `in_rendering_context'
[7999da70-27b5-44b2-b057-1fe9e3d99827] actionview (6.1.7.4) lib/action_view/rendering.rb:116:in `_render_template'
[...]
```
</details>

**Comment by larsUE** [comment]
@carlobeltrame hast du da irgendwas gemacht? Es geht jetzt wieder.

**Comment by carlobeltrame** [comment]
Nein, habe noch nichts gemacht

**Comment by larsUE** [comment]
Ok komisch! In dem Fall musst du auch nichts mehr machen 🍦
